use ControladorNSA
GO

/*BATIMENTO DE QUAIS NSAS NÃO ESTAO BATENDO. PARA RAJADA.
OS IDENTIFICADOR_ID ABAIXO NÃO FORAM MEXIDOS POIS ESTAVAM CORRETOS
542
543
548
549
552
553
558
677
678
683

--IDENTIFICAR QUAIS ESTÃO CORRETOS
select INSA.ID,max(HNSA.NSA) AS [UltimoNSA],INSA.ProximoNSA from NSA.HistoricoNSA HNSA 
	inner join NSA.Identificador INSA ON HNSA.Identificador_ID = INSA.ID
WHERE INSA.Identificador like '%|RAJADA'
GROUP BY INSA.ID,INSA.ProximoNSA
having max(HNSA.NSA) + 1 = INSA.ProximoNSA


AS 2016-11-07 15:04:43.513 ATUALIZEI OS IDS ESPERADOS PARA PARAR COM OS ERROS DE QUEBRA DE NSA DE TODO IDENTIFICADOR QUE TENHA RAJADA
*/
BEGIN TRAN
UPDATE [NSA].[Identificador] SET 
	[ProximoNSA] = Base.ULTIMONSA + 1
FROM 
NSA.IDENTIFICADOR INSA1 
	CROSS APPLY (

SELECT INSA.ID
	,MAX(HNSA.NSA) AS [ULTIMONSA]
	,INSA.PROXIMONSA 
FROM NSA.HISTORICONSA HNSA 
	INNER JOIN NSA.IDENTIFICADOR INSA ON HNSA.IDENTIFICADOR_ID = INSA.ID
WHERE INSA1.ID = INSA.ID
--	AND INSA.IDENTIFICADOR LIKE '%|RAJADA'
GROUP BY INSA.ID,INSA.PROXIMONSA
HAVING MAX(HNSA.NSA) + 1 <> INSA.PROXIMONSA
) Base


--COMMIT
--ROLLBACK

--LISTAR NSAS QUE NÃO ESTÃO COMO O ESPERADO
SELECT INSA.ID,MAX(HNSA.NSA) AS [ULTIMONSA],INSA.PROXIMONSA FROM NSA.HISTORICONSA HNSA 
	INNER JOIN NSA.IDENTIFICADOR INSA ON HNSA.IDENTIFICADOR_ID = INSA.ID
--WHERE INSA.IDENTIFICADOR LIKE '%|RAJADA'
GROUP BY INSA.ID,INSA.PROXIMONSA
HAVING MAX(HNSA.NSA) + 1 <> INSA.PROXIMONSA

/*
QUERYS PARA TESTES
--LISTAR NSAS QUE NÃO ESTÃO COMO O ESPERADO BASEADO NOS ULTIMOS IDS
SELECT INSA.ID,MAX(HNSA.NSA) AS [ULTIMONSA],INSA.PROXIMONSA FROM NSA.HISTORICONSA HNSA 
	INNER JOIN NSA.IDENTIFICADOR INSA ON HNSA.IDENTIFICADOR_ID = INSA.ID
WHERE INSA.IDENTIFICADOR LIKE '%|RAJADA'
AND [INSA].[ID] IN (
540,
541,
544,
545,
546,
547,
550,
551,
554,
555,
556,
557,
673,
674,
675,
676,
679,
680,
681,
682,
694,
695,
696,
697,
698,
699,
700,
701
)
GROUP BY INSA.ID,INSA.PROXIMONSA


*/
--LISTAR NSAS QUE NÃO ESTÃO COMO O ESPERADO
SELECT INSA.ID,MAX(HNSA.NSA) AS [ULTIMONSA],INSA.PROXIMONSA FROM NSA.HISTORICONSA HNSA 
	INNER JOIN NSA.IDENTIFICADOR INSA ON HNSA.IDENTIFICADOR_ID = INSA.ID
--WHERE INSA.IDENTIFICADOR LIKE '%|RAJADA'
GROUP BY INSA.ID,INSA.PROXIMONSA
HAVING MAX(HNSA.NSA) -5 > INSA.PROXIMONSA

SELECT TOP 10 * FROM [ccsEmbratel].email.ControleEnvioEmail ORDER BY 1 DESC 
SELECT TOP 100 * FROM [ControladorNSA].NSA.HistoricoNSA ORDER BY 1 DESC 
SELECT TOP 10 * FROM [ControladorNSA].NSA.HistoricoErroNSA WHERE HistoricoNSA_ID = 95614

UPDATE ControladorNSA.NSA.HistoricoNSA SET Valido = 0 WHERE ID = 95614
INSERT INTO [ControladorNSA].NSA.HistoricoErroNSA VALUES (95614,100,0,0,NULL)

SELECT * FROM [ControladorNSA].NSA.HistoricoNSA WHERE ID = 95614